"""empty message

Revision ID: 51a8e7b7ecca
Revises: 
Create Date: 2019-01-11 22:02:13.052935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51a8e7b7ecca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('award',
    sa.Column('award_id', sa.Integer(), nullable=False),
    sa.Column('award_name', sa.String(length=128), nullable=False),
    sa.Column('award_image', sa.String(length=256), nullable=True),
    sa.Column('award_type', sa.Integer(), nullable=True),
    sa.Column('award_description', sa.Text(), nullable=True),
    sa.Column('award_number', sa.Integer(), nullable=False),
    sa.Column('exchange_token', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('award_id')
    )
    op.create_table('god',
    sa.Column('god_id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.String(length=40), nullable=True),
    sa.Column('ip_addr', sa.String(length=15), nullable=True),
    sa.Column('login_time', sa.DateTime(), nullable=True),
    sa.Column('access_token_expire_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('god_id')
    )
    op.create_table('store',
    sa.Column('store_id', sa.Integer(), nullable=False),
    sa.Column('store_name', sa.String(length=128), nullable=True),
    sa.Column('store_city', sa.String(length=32), nullable=True),
    sa.Column('store_address', sa.String(length=256), nullable=True),
    sa.Column('store_phone', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('store_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('open_id', sa.String(length=28), nullable=False),
    sa.Column('session_key', sa.String(length=24), nullable=False),
    sa.Column('login_time', sa.DateTime(), nullable=True),
    sa.Column('session_id', sa.String(length=40), nullable=False),
    sa.Column('session_id_expire_time', sa.DateTime(), nullable=False),
    sa.Column('can_raffle', sa.Boolean(), nullable=True),
    sa.Column('can_follow', sa.Boolean(), nullable=True),
    sa.Column('user_type', sa.Integer(), nullable=True),
    sa.Column('follow_times', sa.Integer(), nullable=True),
    sa.Column('nickName', sa.String(length=32), nullable=True),
    sa.Column('avatarUrl', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_open_id'), 'user', ['open_id'], unique=True)
    op.create_table('awardrecord',
    sa.Column('awardrecord_id', sa.Integer(), nullable=False),
    sa.Column('award_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('awardrecord_type', sa.Integer(), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('receiver', sa.String(length=16), nullable=True),
    sa.Column('phone', sa.String(length=11), nullable=True),
    sa.Column('address', sa.String(length=256), nullable=True),
    sa.Column('checked', sa.Boolean(), nullable=True),
    sa.Column('check_time', sa.DateTime(), nullable=True),
    sa.Column('awardrecord_token', sa.String(length=128), nullable=False),
    sa.Column('qrcode_image_url', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['award_id'], ['award.award_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('awardrecord_id')
    )
    op.create_table('composition',
    sa.Column('composition_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('composition_type', sa.Integer(), nullable=False),
    sa.Column('composition_msg', sa.String(length=256), nullable=True),
    sa.Column('composition_url', sa.String(length=512), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('composition_id')
    )
    op.create_index(op.f('ix_composition_user_id'), 'composition', ['user_id'], unique=False)
    op.create_table('follow',
    sa.Column('follow_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('follow_id', 'followed_id', 'follower_id')
    )
    op.create_table('userinfo',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('avatarUrl', sa.String(length=512), nullable=True),
    sa.Column('city', sa.String(length=32), nullable=True),
    sa.Column('country', sa.String(length=32), nullable=True),
    sa.Column('gender', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=True),
    sa.Column('nickName', sa.String(length=32), nullable=True),
    sa.Column('province', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userinfo')
    op.drop_table('follow')
    op.drop_index(op.f('ix_composition_user_id'), table_name='composition')
    op.drop_table('composition')
    op.drop_table('awardrecord')
    op.drop_index(op.f('ix_user_open_id'), table_name='user')
    op.drop_table('user')
    op.drop_table('store')
    op.drop_table('god')
    op.drop_table('award')
    # ### end Alembic commands ###
